# Generated by Django 3.0.8 on 2020-07-04 20:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Family',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amazon_id', models.TextField()),
                ('setup_code', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='App',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_id', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='familyconnect.Family')),
            ],
        ),
    ]
